window:
  dimensions:
   columns: 85
   lines: 50

font:
  normal:
    family: Fira Mono for Powerline
  bold:
    family: Fira Mono for Powerline
  italic:
    family: Fira Mono for Powerline
  bold_italic:
    family: Fira Mono for Powerline
  use_thin_strokes: false
  size: 18.0

colors:
  primary:
    background: '#002b36'
    foreground: '#93a1a1'
    dim_foreground: '#a5abb6'
  cursor:
    text: '#002b36'
    cursor: '#93a1a1'
  vi_mode_cursor:
    text: '#002b36'
    cursor: '#93a1a1'
  selection:
    text: CellForeground
    background: '#4c566a'
  search:
    matches:
      foreground: CellBackground
      background: '#2aa198'
    bar:
      background: '#434c5e'
      foreground: '#d8dee9'
  normal:
    black: '#3b4252'
    red: '#dc322f'
    green: '#859900'
    yellow: '#b58900'
    blue: '#268bd2'
    magenta: '#d33682'
    cyan: '#2aa198'
    white: '#e5e9f0'