window:
  dimensions:
   columns: 160 
   lines: 40
    
font:
  normal:
    family: Roboto Mono Light for Powerline
  bold:
    family: Roboto Mono for Powerline
    style: Bold
  italic:
    family: Roboto Mono Light for Powerline
    style: Light Italic
  bold_italic:
    family: Roboto Mono Light for Powerline
    style: Bold Italic
  use_thin_strokes: false
  size: 18.0


draw_bold_text_with_bright_colors: true

colors:
  # Default colors
  primary:
    background: '#282828'
    foreground: '#ebdbb2'

  # Cursor colors
  cursor:
   text: '#EBEBEB'
   cursor: '#FF261E'

  # Normal colors
  normal:
    black:   '#0d0d0d'
    red:     '#FF301B'
    green:   '#A0E521'
    yellow:  '#FFC620'
    blue:    '#1BA6FA'
    magenta: '#d3869b'
    cyan:    '#21DEEF'
    white:   '#EBEBEB'

  # Bright colors
  bright:
    black:   '#6D7070'
    red:     '#FF4352'
    green:   '#B8E466'
    yellow:  '#FFD750'
    blue:    '#1BA6FA'
    magenta: '#AB9DF2'
    cyan:    '#73FBF1'
    white:   '#FEFEF8'
