window:
  dimensions:
   columns: 85
   lines: 50
    
background_opacity: 0.6

font:
  normal:
    family: Fira Mono for Powerline
  bold:
    family: Fira Mono for Powerline
  italic:
    family: Fira Mono for Powerline
  bold_italic:
    family: Fira Mono for Powerline
  use_thin_strokes: false
  size: 18.0

# Colors (Jellybeans)
colors:
  # Default colors
  primary:
    background: '#22282D'
    foreground: '#e4e4e4'

  # Cursor volors
  cursor:
    text: '#000000'
    cursor: '#ffb472'

  # Normal colors
  normal:
    black:   '#a3a3a3'
    red:     '#e98885'
    green:   '#a3c38b'
    yellow:  '#ffc68d'
    blue:    '#a6cae2'
    magenta: '#e7cdfb'
    cyan:    '#00a69f'
    white:   '#e4e4e4'

  # Bright colors
  bright:
    black:   '#c8c8c8'
    red:     '#ffb2b0'
    green:   '#c8e2b9'
    yellow:  '#ffe1af'
    blue:    '#bddff7'
    magenta: '#fce2ff'
    cyan:    '#0bbdb6'
    white:   '#feffff'

  # Selection colors
  selection:
    text: '#5963a2'
    background: '#f6f6f6'
